version: 2.1
orbs:
  node: circleci/node@3.0.1
jobs:
  lint-test:
    executor: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run lint:js
            - run: npm test
workflows:
  matrix-tests:
    jobs:
      - lint-test:
          matrix:
            parameters:
              version:
                - 13.11.0
                - 12.16.0
                - 10.19.0
