version: 2.1
orbs:
  node: circleci/node@3.0.1
commands:
  lint-test:
    executor: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run lint:js
            - run: npm test
jobs:
  node-v8:
    docker:
      - image: node:8
    steps:
      - lint-test
  node-v10:
    docker:
      - image: node:10
    steps:
      - lint-test
  node-v12:
    docker:
      - image: node:12
    steps:
      - lint-test

workflows:
  multi-lint-test:
    jobs:
      - node-v8
      - node-v10
      - node-v12
