version: 2.1
orbs:
  node: circleci/node@3.0.1
jobs:
  build-lint-test:
    executor: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run lint:js
            - run: npm test
workflows:
  build-lint-test:
    jobs:
      - build-lint-test:
          matrix:
            parameters:
              node-version: ["v8.17.0", "10.19.0", "12.18.2"]
